regressionParameters = {'../../biology/pointbem-petsc/src/testSrfOnSurfacePoints':
                            [# Sphere tests [0-8]
                             {'numProcs': 1, 'args': '-num_charges 1 -nmax 25'},
                             {'numProcs': 1, 'args': '-num_charges 10 -nmax 25'},
                             {'numProcs': 1, 'args': '-num_charges 10 -nmax 25 -srf_num 2 -density 2.0'},
                             {'numProcs': 1, 'args': '-num_charges 10 -nmax 25 -srf_num 3 -density 3.0'},
                             {'numProcs': 1, 'args': '-num_charges 10 -nmax 25 -srf_num 4 -density 4.0'},
                             {'numProcs': 1, 'args': '-num_charges 10 -nmax 25 -srf_num 5 -density 5.0'},
                             {'numProcs': 1, 'args': '-num_charges 10 -nmax 25 -srf_num 6 -density 6.0'},
                             {'numProcs': 1, 'args': '-num_charges 10 -nmax 25 -srf_num 8 -density 8.0'},
                             {'numProcs': 1, 'args': '-num_charges 10 -nmax 25 -srf_num 10 -density 10.0'},
                             # Arginine tests [9-16]
                             {'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/arg/arg.pdb -crg_filename ../../jay-asymmetry/saltresidues/arg/jr1.crg -srf_base ../../jay-asymmetry/saltresidues/arg/arg_scaledcharmm_ -srf_num 1'},
                             {'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/arg/arg.pdb -crg_filename ../../jay-asymmetry/saltresidues/arg/jr1.crg -srf_base ../../jay-asymmetry/saltresidues/arg/arg_scaledcharmm_ -srf_num 2'},
                             {'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/arg/arg.pdb -crg_filename ../../jay-asymmetry/saltresidues/arg/jr1.crg -srf_base ../../jay-asymmetry/saltresidues/arg/arg_scaledcharmm_ -srf_num 3'},
                             {'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/arg/arg.pdb -crg_filename ../../jay-asymmetry/saltresidues/arg/jr1.crg -srf_base ../../jay-asymmetry/saltresidues/arg/arg_scaledcharmm_ -srf_num 4'},
                             {'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/arg/arg.pdb -crg_filename ../../jay-asymmetry/saltresidues/arg/jr1.crg -srf_base ../../jay-asymmetry/saltresidues/arg/arg_scaledcharmm_ -srf_num 5'},
                             {'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/arg/arg.pdb -crg_filename ../../jay-asymmetry/saltresidues/arg/jr1.crg -srf_base ../../jay-asymmetry/saltresidues/arg/arg_scaledcharmm_ -srf_num 6'},
                             {'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/arg/arg.pdb -crg_filename ../../jay-asymmetry/saltresidues/arg/jr1.crg -srf_base ../../jay-asymmetry/saltresidues/arg/arg_scaledcharmm_ -srf_num 7'},
                             {'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/arg/arg.pdb -crg_filename ../../jay-asymmetry/saltresidues/arg/jr1.crg -srf_base ../../jay-asymmetry/saltresidues/arg/arg_scaledcharmm_ -srf_num 8'},
                             # Aspartate tests [17-30]
                             {'num': 'asp_0',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 1'},
                             {'num': 'asp_1',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 2'},
                             {'num': 'asp_2',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 3'},
                             {'num': 'asp_3',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 4'},
                             {'num': 'asp_4',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 5'},
                             {'num': 'asp_5',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 6'},
                             {'num': 'asp_6',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 7'},
                             {'num': 'asp_7',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 8'},
                             {'num': 'asp_8',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 12'},
                             {'num': 'asp_9',  'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 16'},
                             {'num': 'asp_10', 'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 20'},
                             {'num': 'asp_11', 'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 24'},
                             {'num': 'asp_12', 'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 28'},
                             {'num': 'asp_13', 'numProcs': 1, 'args': '-is_sphere 0 -pdb_filename ../../jay-asymmetry/saltresidues/asp/asp.pdb -crg_filename ../../jay-asymmetry/saltresidues/asp/jd1.crg -srf_base ../../jay-asymmetry/saltresidues/asp/asp_scaledcharmm_ -srf_num 32'},
                             ],
                        }
